BACKGROUND_COLOR = "#121212"

TEXT_SHADOW_OFFSET = 1
TEXT_SHADOW_COLOR = "#000000"

PAUSE_BACKGROUND_COLOR = "#706B6B"

PAUSE_FONT = ("arial", 40)
PAUSE_TEXT_COLOR = "#FFFFFF"

PATH_FONT = ("arial", 10)
PATH_TEXT_COLOR = "#A0A0A0"

TIMER_FONT = ("arial", 20)
TIMER_TEXT_COLOR = "#A0A0A0"

PROGRESS_FONT = ("arial", 20)
PROGRESS_TEXT_COLOR = "#A0A0A0"

BUTTON_BACKGROUND_COLOR = "#303030"
BUTTON_TEXT_COLOR = "#FFFFFF"
BUTTON_FONT = ("arial", 12)
BUTTON_POSITION_OFFSET = 60
BUTTON_WIDTH = 6
BUTTON_HEIGHT = 1
BUTTON_EDGE_OFFSET = 8

SELECTED_OPTION_BUTTON_COLOR = "#FF0000"
UNSELECTED_OPTION_BUTTON_COLOR = "#FFFFFF"

MAIN_MENU_IMAGESET_BUTTON_WIDTH = 30
MAIN_MENU_IMAGESET_BUTTON_HEIGH = 2
MAIN_MENU_IMAGESET_BUTTON_FONT = ("arial", 12)
MAIN_MENU_MODE_BUTTON_WIDTH = 20
MAIN_MENU_MODE_BUTTON_HEIGH = 2
MAIN_MENU_MODET_BUTTON_FONT = ("arial", 12)
MAIN_MENU_START_BUTTON_WIDTH = 20
MAIN_MENU_START_BUTTON_HEIGHT = 2
MAIN_MENU_START_BUTTON_FONT = ("arial", 12)
MAIN_MENU_START_BUTTON_TEXT = "Start Session"

MAIN_MENU_TABLE_COLS = [500, 300, 300]
MAIN_MENU_TABLE_ROWS = [600, 200]

DEFAULT_CONFIG = """
dimensions="1920x1200"

[mode.classic]
default = "True"
timers = "30s 30s 30s 1m 1m 1m 2m 2m 5m 10m"

[mode.classroom]
manual = "True"

[imageset.example1]
paths = [
#    "path-to-image-folder"
]

[imageset.example2]
paths = [
#    "path-to-image-folder"
]
""".strip()
